# ULTRA-MINIMAL pre-commit configuration per Work Order 49
# Absolute bare-minimum for CI - max velocity, minimum interference
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Ruff format only - no linting barriers
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff-format
