

services:
  scrapersky:
    build:
      context: .
      dockerfile: Dockerfile
    image: scrapersky:v1
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=production
      - UVICORN_RELOAD=false
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# Notes for Production Deployment:
# 1. Supabase is used as the managed database service, providing:
#    - Automatic backups
#    - Point-in-time recovery
#    - High availability
#    - Automatic scaling
#    - Security patches
# 2. All sensitive data is passed via environment variables
# 3. For Kubernetes deployment, use k8s/secrets.yaml and k8s/deployment.yaml
