services:
  scrapersky:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SCRAPER_API_KEY=${SCRAPER_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}  # Updated for consistency
    volumes:
      - ./static:/app/static:ro
      - ./.env:/app/.env:ro  # Mount .env in /app since that's where load_dotenv() looks
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
