services:
  - type: web
    name: scrapersky
    env: docker
    region: oregon # Choose your preferred region
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: UVICORN_RELOAD
        value: false
      - key: SCRAPER_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
    autoDeploy: true
    numInstances: 1 # Adjust based on your needs
    dockerfile: ./Dockerfile
