# Assume Python 3.13
target-version = "py312"

[lint]
select = ["E", "F", "B", "I"]
ignore = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.isort]
known-third-party = ["fastapi", "pydantic", "sqlalchemy", "starlette"]

# Prevent PgBouncer usage
[lint.per-file-ignores]
"**/*.py" = ["ERA001"]

[format]
# Use double quotes for strings.
quote-style = "double"

# Indent with 4 spaces.
indent-style = "space"
line-ending = "auto"
