"""Add deep scan status and error field to Place model

Revision ID: cf984a13c57e
Revises: 74f71834d0a7
Create Date: 2025-04-02 17:55:51.481199

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf984a13c57e'
down_revision: Union[str, None] = '74f71834d0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define enum name and new values
ENUM_NAME = 'place_status_enum'
NEW_STATUSES = [
    'queued_for_deep_scan',
    'processing_deep_scan',
    'deep_scan_complete',
    'deep_scan_failed'
]

def upgrade() -> None:
    # ### commands auto generated by Alembic - focusing on Place model changes ###
    op.add_column('places_staging', sa.Column('deep_scan_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_places_staging_status'), 'places_staging', ['status'], unique=False)
    # ### end Alembic commands ###

    # ### Manually added commands to update the enum type ###
    for status in NEW_STATUSES:
        # Add each new status value to the existing enum type
        # Use 'IF NOT EXISTS' for idempotency
        op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS '{status}'")
    # ### end manually added commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - focusing on Place model changes ###
    op.drop_index(op.f('ix_places_staging_status'), table_name='places_staging')
    op.drop_column('places_staging', 'deep_scan_error')
    # ### end Alembic commands ###

    # ### Manually added commands for downgrade (Caution advised) ###
    # Downgrading enums is complex. Typically requires data migration first.
    # This is a placeholder; real downgrade might need different strategy.
    # For example, renaming to an 'obsolete_' prefix before potential removal later.
    for status in NEW_STATUSES:
        op.execute(f"ALTER TYPE {ENUM_NAME} RENAME VALUE '{status}' TO 'obsolete_{status}'")
    # ### end manually added commands ###
