import uuid
from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, field_validator

from src.models.enums import (
    ContactCurationStatus,
    ContactEmailTypeEnum,
    ContactProcessingStatus,
    CRMProcessingStatus,
    CRMSyncStatus,
    HubSpotProcessingStatus,
    HubSpotSyncStatus,
)

# Base schema for contact fields to be shared
class ContactBase(BaseModel):
    email: str
    email_type: Optional[ContactEmailTypeEnum] = None
    has_gmail: Optional[bool] = None
    context: Optional[str] = None
    source_url: Optional[str] = None
    name: Optional[str] = None
    phone_number: Optional[str] = None
    domain_id: uuid.UUID
    page_id: uuid.UUID
    source_job_id: Optional[uuid.UUID] = None

# Schema for creating a contact
class ContactCreate(ContactBase):
    pass

# Schema for updating a contact - all fields are optional
class ContactUpdate(BaseModel):
    email: Optional[str] = None
    email_type: Optional[ContactEmailTypeEnum] = None
    has_gmail: Optional[bool] = None
    context: Optional[str] = None
    source_url: Optional[str] = None
    name: Optional[str] = None
    phone_number: Optional[str] = None
    contact_curation_status: Optional[ContactCurationStatus] = None
    contact_processing_status: Optional[ContactProcessingStatus] = None
    contact_processing_error: Optional[str] = None
    hubspot_sync_status: Optional[HubSpotSyncStatus] = None
    hubspot_processing_status: Optional[HubSpotProcessingStatus] = None
    hubspot_processing_error: Optional[str] = None
    hubspot_contact_id: Optional[str] = None
    brevo_sync_status: Optional[CRMSyncStatus] = None
    brevo_processing_status: Optional[CRMProcessingStatus] = None
    brevo_processing_error: Optional[str] = None
    brevo_contact_id: Optional[str] = None
    mautic_sync_status: Optional[CRMSyncStatus] = None
    mautic_processing_status: Optional[CRMProcessingStatus] = None
    mautic_processing_error: Optional[str] = None
    mautic_contact_id: Optional[str] = None
    n8n_sync_status: Optional[CRMSyncStatus] = None
    n8n_processing_status: Optional[CRMProcessingStatus] = None
    n8n_processing_error: Optional[str] = None
    n8n_workflow_id: Optional[str] = None

# Schema for reading a contact - includes fields generated by the DB
class ContactRead(ContactBase):
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime
    contact_curation_status: ContactCurationStatus
    contact_processing_status: Optional[ContactProcessingStatus] = None
    contact_processing_error: Optional[str] = None
    hubspot_sync_status: HubSpotSyncStatus
    hubspot_processing_status: Optional[HubSpotProcessingStatus] = None
    hubspot_processing_error: Optional[str] = None
    hubspot_contact_id: Optional[str] = None
    brevo_sync_status: CRMSyncStatus
    brevo_processing_status: Optional[CRMProcessingStatus] = None
    brevo_processing_error: Optional[str] = None
    brevo_contact_id: Optional[str] = None
    mautic_sync_status: CRMSyncStatus
    mautic_processing_status: Optional[CRMProcessingStatus] = None
    mautic_processing_error: Optional[str] = None
    mautic_contact_id: Optional[str] = None
    n8n_sync_status: CRMSyncStatus
    n8n_processing_status: Optional[CRMProcessingStatus] = None
    n8n_processing_error: Optional[str] = None
    n8n_workflow_id: Optional[str] = None
    retry_count: int
    last_retry_at: Optional[datetime] = None
    next_retry_at: Optional[datetime] = None
    last_failed_crm: Optional[str] = None
    
    # DeBounce email validation fields (WO-017)
    debounce_validation_status: Optional[CRMSyncStatus] = None
    debounce_processing_status: Optional[CRMProcessingStatus] = None
    debounce_result: Optional[str] = None
    debounce_score: Optional[int] = None
    debounce_reason: Optional[str] = None
    debounce_suggestion: Optional[str] = None
    debounce_processing_error: Optional[str] = None
    debounce_validated_at: Optional[datetime] = None

    class Config:
        from_attributes = True

# Schemas for batch operations

class ContactCurationBatchStatusUpdateRequest(BaseModel):
    contact_ids: List[uuid.UUID]
    status: ContactCurationStatus

class ContactCurationFilteredUpdateRequest(BaseModel):
    status: ContactCurationStatus
    # Filter fields (all optional)
    contact_curation_status: Optional[ContactCurationStatus] = None
    contact_processing_status: Optional[ContactProcessingStatus] = None
    hubspot_sync_status: Optional[HubSpotSyncStatus] = None
    email_type: Optional[ContactEmailTypeEnum] = None
    domain_id: Optional[uuid.UUID] = None
    page_id: Optional[uuid.UUID] = None
    email_contains: Optional[str] = None
    name_contains: Optional[str] = None
    has_gmail: Optional[bool] = None

class ContactCurationBatchUpdateResponse(BaseModel):
    updated_count: int
    queued_count: int
    hubspot_queued_count: int = 0


class CRMSelectionRequest(BaseModel):
    """Request to mark contacts for CRM sync"""
    contact_ids: List[uuid.UUID]
    crms: List[str]  # ["brevo", "hubspot", "mautic", "n8n"]
    action: str = "select"  # "select" or "unselect"

    model_config = ConfigDict(from_attributes=True)

    @field_validator('action')
    @classmethod
    def validate_action(cls, v):
        if v not in ["select", "unselect"]:
            raise ValueError("action must be 'select' or 'unselect'")
        return v

    @field_validator('crms')
    @classmethod
    def validate_crms(cls, v):
        valid_crms = {"brevo", "mautic", "n8n", "hubspot"}
        invalid = set(v) - valid_crms
        if invalid:
            raise ValueError(f"Invalid CRM names: {invalid}")
        return v
